### ISSUE TITLE
Any comparison with horovod?

### ISSUE THREAD

**Issue by zhuzilin** [cc-hpc-itwm/tarantella#1]
Thank you for your amazing work on accelerating distributed DL training. It seems that your work is similar to horovod. I wonder if you could provide any benchmarks on the comparison between tarantella and horovod? Also, it would be great if you could share any technical advantages of tarantella over horovod. Thank you!

**Comment by plabus** [comment]
Thanks Zilin Zhu for your comment. You can find some of our performance results
at https://tarantella.readthedocs.io/en/latest/why_tarantella.html#performance-results.
There you see strong scalability up to about 100 GPUs and CPUs, respectively.
We have also compared ourselves against Horovod and see already slightly better results,
although we do not take advantage of NVLink, yet. We are planning to release more
performance results in a publication in the near future.

Apart from performance, Tarantella makes it easier to add distributed training
to a TensorFlow model. In particular, you have to make fewer modifications
to your code, through the use of our automatically distributed datasets and callbacks,
model saving/loading/checkpointing etc. Additionally, we are planning to
support automatic model parallelism, as well, which will allow you to train
models that do not fit into a single GPU without having to take care of how to split them.

You can find some more information in my MLHPCS talk (including some older benchmark results)
here: https://keuperj.github.io/MLHPCS/invited_3.html

**Comment by zhuzilin** [comment]
Thank you for your information!
